export const mockCourses = [
  { courseCode: "ENG101", courseName: "English Communication", maxSlots: 30, currentSlots: 18 },
  { courseCode: "MTH202", courseName: "Advanced Mathematics", maxSlot: 40, currentSlot: 40 },
  { courseCode: "PHY103", courseName: "Physics Basics", maxSlot: 25, currentSlot: 22 },
  { courseCode: "CHE104", courseName: "Chemistry Fundamentals", maxSlot: 30, currentSlot: 20 },
  { courseCode: "BIO105", courseName: "Biology Introduction", maxSlot: 35, currentSlot: 28 },
  { courseCode: "HIS106", courseName: "World History", maxSlot: 40, currentSlot: 30 },
  { courseCode: "GEO107", courseName: "Geography Basics", maxSlot: 25, currentSlot: 18 },
  { courseCode: "CS108", courseName: "Computer Science I", maxSlot: 50, currentSlot: 45 },
  { courseCode: "ENG109", courseName: "English Literature", maxSlot: 30, currentSlot: 25 },
  { courseCode: "MTH210", courseName: "Calculus II", maxSlot: 40, currentSlot: 32 },
  { courseCode: "PHY211", courseName: "Physics II", maxSlot: 30, currentSlot: 28 },
  { courseCode: "CHE212", courseName: "Organic Chemistry", maxSlot: 35, currentSlot: 27 },
  { courseCode: "BIO213", courseName: "Genetics", maxSlot: 25, currentSlot: 20 },
  { courseCode: "HIS214", courseName: "Modern History", maxSlot: 40, currentSlot: 33 },
  { courseCode: "GEO215", courseName: "Physical Geography", maxSlot: 30, currentSlot: 22 },
  { courseCode: "CS216", courseName: "Data Structures", maxSlot: 50, currentSlot: 40 },
  { courseCode: "ENG217", courseName: "Creative Writing", maxSlot: 25, currentSlot: 20 },
  { courseCode: "MTH218", courseName: "Linear Algebra", maxSlot: 35, currentSlot: 30 },
  { courseCode: "PHY219", courseName: "Electromagnetism", maxSlot: 30, currentSlot: 25 },
  { courseCode: "CS220", courseName: "Algorithms", maxSlot: 50, currentSlot: 45 },
];